#!/usr/bin/env bash
# パイプライン全自動実行スクリプト
# Usage: ./scripts/pipeline.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS="$REPO_ROOT/scripts"
MAX_AUDIT_LOOPS=3

log()  { echo "[pipeline] $*"; }
die()  { echo "[pipeline] ERROR: $*" >&2; exit 1; }
step() { echo; echo "════════════════════════════════════════"; echo "[pipeline] STEP: $*"; echo "════════════════════════════════════════"; }

# ── 前提チェック ──────────────────────────────────────────────────────────────

command -v claude &>/dev/null || die "'claude' CLI が見つかりません"
command -v gh     &>/dev/null || die "'gh' CLI が見つかりません（GitHub CLI）"

# ── STEP 1: アーキ（設計書生成） ──────────────────────────────────────────────

step "1/5 アーキ（設計書生成）"
bash "$SCRIPTS/agents.sh" architect

# ── STEP 2: ビルド（実装） ────────────────────────────────────────────────────

step "2/5 ビルド（実装）"
FEATURE_BRANCH="$(bash "$SCRIPTS/agents.sh" engineer)"
log "実装ブランチ: $FEATURE_BRANCH"

# ── STEP 3: オーディ（監査ループ） ───────────────────────────────────────────

step "3/5 オーディ（監査）"
audit_loop=0
audit_passed=false

while [[ $audit_loop -lt $MAX_AUDIT_LOOPS ]]; do
  audit_loop=$((audit_loop + 1))
  log "監査 ${audit_loop}/${MAX_AUDIT_LOOPS} 回目"

  if bash "$SCRIPTS/agents.sh" auditor; then
    audit_passed=true
    break
  fi

  if [[ $audit_loop -lt $MAX_AUDIT_LOOPS ]]; then
    log "アーキに差し戻し → 設計書を再生成します..."
    bash "$SCRIPTS/agents.sh" architect
    log "ビルドに差し戻し → 再実装します..."
    bash "$SCRIPTS/agents.sh" engineer
  fi
done

if [[ "$audit_passed" == false ]]; then
  die "監査が ${MAX_AUDIT_LOOPS} 回通過しませんでした。ダイチに判断を委ねます。"
fi

# ── STEP 4: PR 作成 ───────────────────────────────────────────────────────────

step "4/5 PR 作成"

KNOWLEDGE="$REPO_ROOT/docs/knowledge"
DESIGN_FILE="$KNOWLEDGE/design/design.md"

# 最新監査ログを取得
LATEST_AUDIT="$(ls -t "$KNOWLEDGE/audit-log"/audit_*.md 2>/dev/null | head -1 || echo '')"
AUDIT_SUMMARY=""
if [[ -n "$LATEST_AUDIT" ]]; then
  AUDIT_SUMMARY="$(grep -A2 '## サマリー' "$LATEST_AUDIT" | tail -n +2 || echo '（取得失敗）')"
fi

# 設計書から概要を抽出
DESIGN_OVERVIEW=""
if [[ -f "$DESIGN_FILE" ]]; then
  DESIGN_OVERVIEW="$(sed -n '/^## 概要/,/^## /p' "$DESIGN_FILE" | head -20 | sed '$d')"
fi

git -C "$REPO_ROOT" push origin "$FEATURE_BRANCH"

gh pr create \
  --base main \
  --head "$FEATURE_BRANCH" \
  --title "feat: $(basename "$FEATURE_BRANCH")" \
  --body "$(cat <<BODY
## 実装内容

$DESIGN_OVERVIEW

## 要件との対応

\`docs/knowledge/requirements/\` に記載の要件を実装。

## 設計上の主な判断

設計書（\`docs/knowledge/design/design.md\`）を参照。

## 監査結果

$AUDIT_SUMMARY

> 監査ログ: \`$LATEST_AUDIT\`

---
🤖 Generated by pipeline.sh（アーキ→ビルド→オーディ）
BODY
)"

log "PR を作成しました"

# ── STEP 5: 完了通知 ──────────────────────────────────────────────────────────

step "5/5 完了"
log "パイプライン完了！ PR をコパ（GitHub Copilot）がレビュー後、ダイチが動作確認してください。"
