#!/usr/bin/env bash
# パイプライン全自動実行スクリプト
# Usage: ./scripts/pipeline.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS="$REPO_ROOT/scripts"
MAX_TEST_LOOPS=3   # テスタ失敗 → ビルド差し戻しの最大回数
MAX_AUDIT_LOOPS=3  # オーディ失敗 → アーキ差し戻しの最大回数

log()  { echo "[pipeline] $*"; }
die()  { echo "[pipeline] ERROR: $*" >&2; exit 1; }
step() { echo; echo "════════════════════════════════════════"; echo "[pipeline] STEP: $*"; echo "════════════════════════════════════════"; }

# ── 前提チェック ──────────────────────────────────────────────────────────────

command -v claude &>/dev/null || die "'claude' CLI が見つかりません"
command -v gh     &>/dev/null || die "'gh' CLI が見つかりません（GitHub CLI）"

# ── STEP 1: アーキ（設計書生成） ──────────────────────────────────────────────

step "1/5 アーキ（設計書生成）"
bash "$SCRIPTS/agents.sh" architect

# ── STEP 2: ビルド（実装）+ STEP 3: テスタ（E2E）ループ ───────────────────────
# テスタ失敗 → ビルドのみ差し戻し（アーキは触らない）

step "2-3/5 ビルド → テスタ（ループ）"
FEATURE_BRANCH="$(bash "$SCRIPTS/agents.sh" engineer | tail -1)"
log "実装ブランチ: $FEATURE_BRANCH"

test_loop=0
test_passed=false

while [[ $test_loop -lt $MAX_TEST_LOOPS ]]; do
  test_loop=$((test_loop + 1))
  log "E2E テスト ${test_loop}/${MAX_TEST_LOOPS} 回目"

  if bash "$SCRIPTS/agents.sh" tester; then
    test_passed=true
    break
  fi

  if [[ $test_loop -lt $MAX_TEST_LOOPS ]]; then
    log "テスト不合格 → ビルドに差し戻します..."
    FEATURE_BRANCH="$(bash "$SCRIPTS/agents.sh" engineer | tail -1)"
    log "再実装ブランチ: $FEATURE_BRANCH"
  fi
done

if [[ "$test_passed" == false ]]; then
  die "E2E テストが ${MAX_TEST_LOOPS} 回通過しませんでした。ダイチに判断を委ねます。"
fi

# ── STEP 4: オーディ（セキュリティ監査ループ） ────────────────────────────────
# オーディ失敗 → アーキ・ビルド両方に差し戻し

step "4/5 オーディ（セキュリティ監査）"
audit_loop=0
audit_passed=false

while [[ $audit_loop -lt $MAX_AUDIT_LOOPS ]]; do
  audit_loop=$((audit_loop + 1))
  log "監査 ${audit_loop}/${MAX_AUDIT_LOOPS} 回目"

  if bash "$SCRIPTS/agents.sh" auditor; then
    audit_passed=true
    break
  fi

  if [[ $audit_loop -lt $MAX_AUDIT_LOOPS ]]; then
    log "監査不通過 → アーキに差し戻し → 設計書を再生成します..."
    bash "$SCRIPTS/agents.sh" architect
    log "ビルドに差し戻し → 再実装します..."
    FEATURE_BRANCH="$(bash "$SCRIPTS/agents.sh" engineer | tail -1)"
    log "新ブランチ: $FEATURE_BRANCH"
    log "テスタを再実行します..."
    bash "$SCRIPTS/agents.sh" tester || log "テスト再実行で失敗（監査ループ継続）"
  fi
done

if [[ "$audit_passed" == false ]]; then
  die "監査が ${MAX_AUDIT_LOOPS} 回通過しませんでした。ダイチに判断を委ねます。"
fi

# ── STEP 5: PR 作成 ───────────────────────────────────────────────────────────

step "5/5 PR 作成"

KNOWLEDGE="$REPO_ROOT/docs/knowledge"
DESIGN_FILE="$KNOWLEDGE/design.md"

LATEST_AUDIT="$(ls -t "$KNOWLEDGE/audit-log"/audit_*.md 2>/dev/null | head -1 || echo '')"
LATEST_TEST="$(ls -t "$KNOWLEDGE/test-log"/test_*.md 2>/dev/null | head -1 || echo '')"
AUDIT_SUMMARY=""
TEST_SUMMARY=""

if [[ -n "$LATEST_AUDIT" ]]; then
  AUDIT_SUMMARY="$(grep -A2 '## サマリー' "$LATEST_AUDIT" | tail -n +2 || echo '（取得失敗）')"
fi
if [[ -n "$LATEST_TEST" ]]; then
  TEST_SUMMARY="$(grep -A3 '## サマリー' "$LATEST_TEST" | tail -n +2 || echo '（取得失敗）')"
fi

DESIGN_OVERVIEW=""
if [[ -f "$DESIGN_FILE" ]]; then
  DESIGN_OVERVIEW="$(sed -n '/^## 概要/,/^## /p' "$DESIGN_FILE" | head -20 | sed '$d')"
fi

git -C "$REPO_ROOT" push origin "$FEATURE_BRANCH"

gh pr create \
  --base main \
  --head "$FEATURE_BRANCH" \
  --title "feat: $(basename "$FEATURE_BRANCH")" \
  --body "$(cat <<BODY
## 実装内容

$DESIGN_OVERVIEW

## 要件との対応

\`docs/knowledge/requirements.md\` に記載の要件を実装。

## 設計上の主な判断

設計書（\`docs/knowledge/design.md\`）を参照。

## E2E テスト結果

$TEST_SUMMARY

> テストログ: \`$LATEST_TEST\`

## セキュリティ監査結果

$AUDIT_SUMMARY

> 監査ログ: \`$LATEST_AUDIT\`

---
🤖 Generated by pipeline.sh（アーキ→ビルド→テスタ→オーディ）
BODY
)"

log "PR を作成しました"

# ── 完了 ──────────────────────────────────────────────────────────────────────

step "完了"
log "パイプライン完了！ PR をコパ（GitHub Copilot）がレビュー後、ダイチが動作確認してください。"
